### PR TITLE
Formy form

### PR DESCRIPTION
**Pull request by yoshuawuyts**
wip - not sure about any of the `.sibyl` stuff - should we put it in `.gitignore`?

### Changes
- moved all client side logic to separate files
- changed all event names to constants
- changed the sibyl stream to a stateful sibyl file
- replaced the sse upload with a json upload (which returns a token that we can connect to the sse stream)

### Todo
- [x] create the server endpoint to reconnect to the stream
- [x] wrap up client logic to connect to the stream

### CODE REVIEW

**Comment by nokome** [comment]
Nice! :+1: I like the refactoring into separate files and not having a separate `events.js` - that was bothering me before - feels like much better encapsulation this way. 

Why not go one step further and do the same with view functions? For example, I think I would find it much easier to understand an work on the code if `createLinks` was a function called `view` exported by `embed.js`.

I've made some commits to reverse some of your changes - notes therein.

**Comment by nokome** [comment]
OK, so it looks like running `npm start` is creating `.sibyl` and deleting those symlinks.

**Comment by yoshuawuyts** [comment]
> Why not go one step further and do the same with view functions? For example, I think I would find it much easier to understand an work on the code if createLinks was a function called view exported by embed.js.

I'm a bit on the fence about this - the way I'd approach this would probably be to turn it into a separate component (e.g. [microcomponent](https://github.com/yoshuawuyts/microcomponent)) and like keep all logic incapsulated. I suggest we hold off on that for a lil until after the deadline - but I agree with the main idea.

The reason why we didn't use it from the get-go was because the code was broken; but I fixed it over the weekend (: Might be cool to give it a shot again next week (:

Code looks good btw, thanks!

**Comment by nokome** [comment]
Ouuch! I'm sorry the missing symlinks is my fault - it's done by `sibyl.sh` - and it screws up the local `node_modules/.bin` too. I had to do a new `npm install` after deleting `node_modules`. I have pushed a fix to master and am working on more safeguards now. Again, sorry if this caused you issues! :(

**Comment by yoshuawuyts** [comment]
@nokome no worries!

This patch works now by the way; I'm going to continue with fixing the dropdown on top of this. Review welcome!

**Pull request merged**
