### PR TITLE
kubernetes flag enabled

### PR DESCRIPTION
**Pull request by yoshuawuyts**
Adds a flag so we can set it's running in kubernetes

### CODE REVIEW

**Comment by nokome** [comment]
@yoshuawuyts : thanks for this! It conflicts with some other changes that I made. Lets leave this unmerged for now and I'll come back to it later.

**Comment by yoshuawuyts** [comment]
cool, sounds good!

**Comment by yoshuawuyts** [comment]
Spring cleaning time 🕥 - PR has been inactive for a while, closing!

**Comment by nokome** [comment]
Thanks for this. Lots of spring cleaning to be done around here! ...and elsewhere, will fill you in on changes soon.

**Pull request closed without merging**
